version: '2'
services:
    externalmoduleproject-app:
        image: externalmoduleproject
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://externalmoduleproject-mysql:3306/externalmoduleproject?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    externalmoduleproject-mysql:
        extends:
            file: mysql.yml
            service: externalmoduleproject-mysql
